ai_provider:
  provider: ollama
  ollama_host: http://localhost:11434
  embedding_model: nomic-embed-text
  llm_model: llama3:8b

# cada dev/empresa agrega los repos que quiere analizar acá
projects:
  - id: microservices-demo
    name: "Online Boutique (Google Demo)"
    repo_path: "../microservices-demo"
